"""
codegen.py — x86-64 Assembly Code Generator (NASM syntax)
==========================================================
Phase 6 of the compiler.

Translates the flat list of TAC instructions into x86-64 assembly in
NASM syntax.  The output can be assembled with:

    nasm -f elf64 output.asm -o output.o
    ld output.o -o output          (on Linux)

Design decisions (kept simple for teaching):
  • Every variable and temporary lives on the stack (no register
    allocation optimisation — much easier to understand).
  • A helper routine `print_int` converts an integer in rdi to its
    decimal string and writes it to stdout via the `write` syscall.
  • Uses Linux x86-64 syscall ABI (syscall numbers 1 for write,
    60 for exit).

Key concepts demonstrated:
  • Stack-frame variable mapping  (RBP - offset)
  • Translating arithmetic into mov / add / sub / imul / idiv
  • Conditional and unconditional jumps for control flow
  • A self-contained print_int routine using the stack as a buffer
"""


class CodeGenerator:
    """Translate TAC → NASM x86-64 assembly."""

    def __init__(self, symbol_table):
        self.symtab = symbol_table
        self.asm_lines = []          # accumulated assembly lines
        self._var_offset = {}        # variable name → stack offset
        self._next_offset = 8        # next available offset from RBP

    # ── Stack Variable Mapping ───────────────────────────────────────

    def _get_offset(self, name):
        """
        Return the RBP-relative offset for *name*.
        Allocates a new 8-byte slot if this is the first access.
        """
        if name not in self._var_offset:
            self._var_offset[name] = self._next_offset
            self._next_offset += 8
        return self._var_offset[name]

    def _var_loc(self, name):
        """Return the NASM memory operand for a variable, e.g. [rbp-16]."""
        return f"[rbp-{self._get_offset(name)}]"

    # ── Helpers ──────────────────────────────────────────────────────

    def _emit(self, line):
        self.asm_lines.append(line)

    def _is_number(self, s):
        """Check if string represents an integer literal."""
        try:
            int(s)
            return True
        except ValueError:
            return False

    def _load_operand(self, operand, register):
        """
        Emit instructions to load *operand* (a variable name or integer
        literal) into the given *register*.
        """
        if self._is_number(operand):
            self._emit(f"    mov {register}, {operand}")
        else:
            self._emit(f"    mov {register}, {self._var_loc(operand)}")

    # ── Public Entry Point ───────────────────────────────────────────

    def generate(self, tac_instructions):
        """
        Generate complete NASM assembly from the TAC instruction list.
        Returns the assembly as a single string.
        """
        # -- Pre-scan: allocate stack slots for every name that appears.
        self._prescan(tac_instructions)

        # -- Boilerplate header
        self._emit_header()

        # -- Translate each TAC instruction
        for instr in tac_instructions:
            self._emit(f"    ; TAC: {instr}")       # embed TAC as comment
            self._translate(instr)

        # -- Boilerplate footer (exit)
        self._emit_footer()

        # -- print_int subroutine
        self._emit_print_int()

        return '\n'.join(self.asm_lines) + '\n'

    # ── Pre-scan ─────────────────────────────────────────────────────

    def _prescan(self, tac_instructions):
        """Allocate stack slots for variables and temporaries."""
        for instr in tac_instructions:
            parts = instr.replace(':', '').split()
            for token in parts:
                # Skip keywords, operators, labels, numbers
                if token in ('if', 'goto', 'print', '=',
                             '+', '-', '*', '/',
                             '==', '!=', '<', '>', '<=', '>='):
                    continue
                if self._is_number(token):
                    continue
                if token.startswith('L') and token[1:].isdigit():
                    continue  # label like L0, L1
                # It's a variable or temporary — allocate a slot
                self._get_offset(token)

    # ── Header / Footer ──────────────────────────────────────────────

    def _emit_header(self):
        stack_size = self._next_offset
        # Align to 16 bytes (ABI requirement)
        stack_size = ((stack_size + 15) // 16) * 16

        self._emit("; -- Generated by MiniCompiler (x86-64, NASM) --")
        self._emit("section .text")
        self._emit("global _start")
        self._emit("")
        self._emit("_start:")
        self._emit("    ; ----- set up stack frame -----")
        self._emit("    push rbp")
        self._emit("    mov rbp, rsp")
        self._emit(f"    sub rsp, {stack_size}")
        self._emit("")

    def _emit_footer(self):
        self._emit("")
        self._emit("    ; ----- exit(0) -----")
        self._emit("    mov rax, 60        ; syscall: exit")
        self._emit("    xor rdi, rdi       ; status = 0")
        self._emit("    syscall")
        self._emit("")

    # ── TAC → Assembly Translation ───────────────────────────────────

    def _translate(self, instr):
        """Translate a single TAC instruction to assembly."""

        # ── Label:  e.g. "L0:"
        if instr.endswith(':'):
            label = instr[:-1]
            self._emit(f"{label}:")
            return

        # ── Conditional jump:  "if <cond> goto <label>"
        if instr.startswith('if '):
            self._translate_if(instr)
            return

        # ── Unconditional jump:  "goto <label>"
        if instr.startswith('goto '):
            label = instr.split()[1]
            self._emit(f"    jmp {label}")
            return

        # ── Print:  "print <operand>"
        if instr.startswith('print '):
            operand = instr.split()[1]
            self._load_operand(operand, 'rdi')
            self._emit("    call print_int")
            return

        # ── Assignment:  "result = ..."
        if '=' in instr:
            self._translate_assign(instr)
            return

    def _translate_assign(self, instr):
        """Handle  result = operand   or   result = left op right."""
        parts = instr.split()
        result = parts[0]

        if len(parts) == 3:
            # Simple copy:  result = operand
            operand = parts[2]
            self._load_operand(operand, 'rax')
            self._emit(f"    mov {self._var_loc(result)}, rax")

        elif len(parts) == 5:
            # Arithmetic:  result = left op right
            left, op, right = parts[2], parts[3], parts[4]
            self._load_operand(left, 'rax')

            if op == '+':
                self._load_operand(right, 'rbx')
                self._emit("    add rax, rbx")
            elif op == '-':
                self._load_operand(right, 'rbx')
                self._emit("    sub rax, rbx")
            elif op == '*':
                self._load_operand(right, 'rbx')
                self._emit("    imul rax, rbx")
            elif op == '/':
                self._emit("    cqo               ; sign-extend rax -> rdx:rax")
                self._load_operand(right, 'rbx')
                self._emit("    idiv rbx           ; rax = rdx:rax / rbx")
            elif op in ('==', '!=', '<', '>', '<=', '>='):
                self._load_operand(right, 'rbx')
                self._emit("    cmp rax, rbx")
                self._emit("    xor rax, rax       ; clear rax")
                jump_map = {
                    '==': 'sete',  '!=': 'setne',
                    '<':  'setl',  '>':  'setg',
                    '<=': 'setle', '>=': 'setge',
                }
                self._emit(f"    {jump_map[op]} al        ; set al = 1 if true")

            self._emit(f"    mov {self._var_loc(result)}, rax")

    def _translate_if(self, instr):
        """Handle  'if <cond_var> goto <label>'."""
        parts = instr.split()
        cond_var = parts[1]
        label = parts[3]
        self._load_operand(cond_var, 'rax')
        self._emit("    cmp rax, 0")
        self._emit(f"    jne {label}         ; jump if condition is true")

    # ── print_int subroutine ─────────────────────────────────────────

    def _emit_print_int(self):
        """
        Emit a small subroutine that prints the signed 64-bit integer
        in RDI to stdout, followed by a newline.

        Algorithm:
          1. Handle negative: if rdi < 0, print '-', negate rdi.
          2. Divide by 10 repeatedly, push digits on stack.
          3. Pop and write each digit character.
          4. Write '\\n'.
        """
        self._emit("; -- print_int subroutine ----------------------")
        self._emit("print_int:")
        self._emit("    push rbp")
        self._emit("    mov rbp, rsp")
        self._emit("    sub rsp, 32            ; local buffer space")
        self._emit("    mov rax, rdi           ; number to print")
        self._emit("    ; Handle negative numbers")
        self._emit("    test rax, rax")
        self._emit("    jns .pi_positive")
        self._emit("    ; Print '-' character")
        self._emit("    push rax")
        self._emit("    mov byte [rbp-32], '-'")
        self._emit("    mov rax, 1             ; syscall: write")
        self._emit("    mov rdi, 1             ; fd: stdout")
        self._emit("    lea rsi, [rbp-32]")
        self._emit("    mov rdx, 1")
        self._emit("    syscall")
        self._emit("    pop rax")
        self._emit("    neg rax                ; make positive")
        self._emit(".pi_positive:")
        self._emit("    ; Convert integer to decimal string (reverse)")
        self._emit("    lea rdi, [rbp-1]       ; end of buffer")
        self._emit("    mov byte [rdi], 10     ; newline at the end")
        self._emit("    dec rdi")
        self._emit("    mov rcx, 0             ; digit count")
        self._emit("    mov r8, 10             ; divisor")
        self._emit(".pi_loop:")
        self._emit("    xor rdx, rdx")
        self._emit("    div r8                 ; rax / 10, remainder in rdx")
        self._emit("    add dl, '0'            ; convert to ASCII")
        self._emit("    mov [rdi], dl")
        self._emit("    dec rdi")
        self._emit("    inc rcx")
        self._emit("    test rax, rax")
        self._emit("    jnz .pi_loop")
        self._emit("    ; Write the digits + newline")
        self._emit("    inc rdi                ; rdi points to first digit")
        self._emit("    inc rcx                ; include the newline")
        self._emit("    mov rax, 1             ; syscall: write")
        self._emit("    mov rsi, rdi           ; buffer start")
        self._emit("    mov rdx, rcx           ; length")
        self._emit("    mov rdi, 1             ; fd: stdout")
        self._emit("    syscall")
        self._emit("    mov rsp, rbp")
        self._emit("    pop rbp")
        self._emit("    ret")


# ─── Convenience ─────────────────────────────────────────────────────

def generate_assembly(tac_instructions, symbol_table):
    """Generate x86-64 NASM assembly from TAC and return it as a string."""
    gen = CodeGenerator(symbol_table)
    return gen.generate(tac_instructions)
