; -- Generated by MiniCompiler (x86-64, NASM) --
section .text
global _start

_start:
    ; ----- set up stack frame -----
    push rbp
    mov rbp, rsp
    sub rsp, 160

    ; TAC: x = 10
    mov rax, 10
    mov [rbp-8], rax
    ; TAC: y = 20
    mov rax, 20
    mov [rbp-16], rax
    ; TAC: t0 = y * 2
    mov rax, [rbp-16]
    mov rbx, 2
    imul rax, rbx
    mov [rbp-24], rax
    ; TAC: t1 = x + t0
    mov rax, [rbp-8]
    mov rbx, [rbp-24]
    add rax, rbx
    mov [rbp-32], rax
    ; TAC: z = t1
    mov rax, [rbp-32]
    mov [rbp-40], rax
    ; TAC: print z
    mov rdi, [rbp-40]
    call print_int
    ; TAC: t2 = z > 50
    mov rax, [rbp-40]
    mov rbx, 50
    cmp rax, rbx
    xor rax, rax       ; clear rax
    setg al        ; set al = 1 if true
    mov [rbp-48], rax
    ; TAC: if t2 goto L0
    mov rax, [rbp-48]
    cmp rax, 0
    jne L0         ; jump if condition is true
    ; TAC: goto L1
    jmp L1
    ; TAC: L0:
L0:
    ; TAC: t3 = z - 50
    mov rax, [rbp-40]
    mov rbx, 50
    sub rax, rbx
    mov [rbp-56], rax
    ; TAC: result = t3
    mov rax, [rbp-56]
    mov [rbp-64], rax
    ; TAC: goto L2
    jmp L2
    ; TAC: L1:
L1:
    ; TAC: t4 = z + 50
    mov rax, [rbp-40]
    mov rbx, 50
    add rax, rbx
    mov [rbp-72], rax
    ; TAC: result = t4
    mov rax, [rbp-72]
    mov [rbp-64], rax
    ; TAC: L2:
L2:
    ; TAC: print result
    mov rdi, [rbp-64]
    call print_int
    ; TAC: sum = 0
    mov rax, 0
    mov [rbp-80], rax
    ; TAC: i = 1
    mov rax, 1
    mov [rbp-88], rax
    ; TAC: L3:
L3:
    ; TAC: t5 = i <= 5
    mov rax, [rbp-88]
    mov rbx, 5
    cmp rax, rbx
    xor rax, rax       ; clear rax
    setle al        ; set al = 1 if true
    mov [rbp-96], rax
    ; TAC: if t5 goto L4
    mov rax, [rbp-96]
    cmp rax, 0
    jne L4         ; jump if condition is true
    ; TAC: goto L5
    jmp L5
    ; TAC: L4:
L4:
    ; TAC: t6 = sum + i
    mov rax, [rbp-80]
    mov rbx, [rbp-88]
    add rax, rbx
    mov [rbp-104], rax
    ; TAC: sum = t6
    mov rax, [rbp-104]
    mov [rbp-80], rax
    ; TAC: t7 = i + 1
    mov rax, [rbp-88]
    mov rbx, 1
    add rax, rbx
    mov [rbp-112], rax
    ; TAC: i = t7
    mov rax, [rbp-112]
    mov [rbp-88], rax
    ; TAC: goto L3
    jmp L3
    ; TAC: L5:
L5:
    ; TAC: print sum
    mov rdi, [rbp-80]
    call print_int
    ; TAC: t8 = x + y
    mov rax, [rbp-8]
    mov rbx, [rbp-16]
    add rax, rbx
    mov [rbp-120], rax
    ; TAC: t9 = z - 10
    mov rax, [rbp-40]
    mov rbx, 10
    sub rax, rbx
    mov [rbp-128], rax
    ; TAC: t10 = t8 * t9
    mov rax, [rbp-120]
    mov rbx, [rbp-128]
    imul rax, rbx
    mov [rbp-136], rax
    ; TAC: t11 = t10 / 2
    mov rax, [rbp-136]
    cqo               ; sign-extend rax -> rdx:rax
    mov rbx, 2
    idiv rbx           ; rax = rdx:rax / rbx
    mov [rbp-144], rax
    ; TAC: answer = t11
    mov rax, [rbp-144]
    mov [rbp-152], rax
    ; TAC: print answer
    mov rdi, [rbp-152]
    call print_int

    ; ----- exit(0) -----
    mov rax, 60        ; syscall: exit
    xor rdi, rdi       ; status = 0
    syscall

; -- print_int subroutine ----------------------
print_int:
    push rbp
    mov rbp, rsp
    sub rsp, 32            ; local buffer space
    mov rax, rdi           ; number to print
    ; Handle negative numbers
    test rax, rax
    jns .pi_positive
    ; Print '-' character
    push rax
    mov byte [rbp-32], '-'
    mov rax, 1             ; syscall: write
    mov rdi, 1             ; fd: stdout
    lea rsi, [rbp-32]
    mov rdx, 1
    syscall
    pop rax
    neg rax                ; make positive
.pi_positive:
    ; Convert integer to decimal string (reverse)
    lea rdi, [rbp-1]       ; end of buffer
    mov byte [rdi], 10     ; newline at the end
    dec rdi
    mov rcx, 0             ; digit count
    mov r8, 10             ; divisor
.pi_loop:
    xor rdx, rdx
    div r8                 ; rax / 10, remainder in rdx
    add dl, '0'            ; convert to ASCII
    mov [rdi], dl
    dec rdi
    inc rcx
    test rax, rax
    jnz .pi_loop
    ; Write the digits + newline
    inc rdi                ; rdi points to first digit
    inc rcx                ; include the newline
    mov rax, 1             ; syscall: write
    mov rsi, rdi           ; buffer start
    mov rdx, rcx           ; length
    mov rdi, 1             ; fd: stdout
    syscall
    mov rsp, rbp
    pop rbp
    ret
